NONE = 'O'
PAD = "[PAD]"
UNK = "[UNK]"

# for BERT
CLS = '[CLS]'
SEP = '[SEP]'

# the tree structure that describes labeled events
ace_structure = [        
            [["Life",None],["Life:Die",None]],
            [["Life",None],["Life:Injure",None]],
            [["Movement", None],["Movement:Transport",None]],
            [["Transaction",None],["Transaction:Transfer-Money",None]],
            [["Conflict",None],["Conflict:Attack",None]],
            [["Contact",None],["Contact:Phone-Write",None]],
            [['Personnel',None],['Personnel:Elect',None]],
            [["Personnel",None],["Personnel:End-Position",None]],
            [["Justice",None],["Justice:Trial-Hearing",None]],
            [['Contact',None],['Contact:Meet',None]],
            
            [["event_type",None],["Life",None]],
            [["event_type",None],["Movement",None]],
            [["event_type",None],["Transaction",None]],
            [["event_type",None],["Conflict",None]],
            [["event_type",None],["Contact",None]],
            [["event_type",None],["Personnel",None]],
            [["event_type",None],["Justice",None]]
    ]
# describes the golden unlabeled events tree structure
ace_structure_test = [
    [["Justice",None],["Justice:Pardon",None]],
    [['Business',None],['Business:End-Org',None]],
    [['Justice',None],['Justice:Convict',None]],
    [['Justice',None],['Justice:Sentence',None]],
    [['Justice',None],['Justice:Acquit',None]],
    [['Conflict',None],['Conflict:Demonstrate',None]],
    [["Business",None],["Business:Declare-Bankruptcy",None]],
    [["Business",None],["Business:Merge-Org",None]],
    [["Business",None],["Business:Start-Org",None]],
    [['Transaction',None],['Transaction:Transfer-Ownership',None]],
    [["Justice",None],["Justice:Release-Parole",None]],
    [["Justice",None],["Justice:Appeal",None]],
    [["Justice",None],["Justice:Execute",None]],
    [["Justice",None],["Justice:Extradite",None]],
    [["Justice",None],["Justice:Fine",None]],
    [["Personnel",None],["Personnel:Nominate",None]],
    [["Personnel",None],["Personnel:Start-Position",None]],
    [["Life",None],["Life:Marry",None]],
    [["Life",None],["Life:Be-Born",None]],
    [["Life",None],["Life:Divorce",None]],
    [["Justice",None],["Justice:Charge-Indict",None]],
    [["Justice",None],["Justice:Arrest-Jail",None]],
    [["Justice",None],["Justice:Sue",None]],
]
# the instance number contains in training dataset
NUM_LABEL_ACE = {"Conflict:Attack":1245,
                "Movement:Transport":603,
                "Life:Die":511,
                "Contact:Meet":200,
                "Personnel:End-Position":158,
                "Personnel:Elect":150,
                "Transaction:Transfer-Money":127,
                "Life:Injure":127,
                "Contact:Phone-Write":112,
                "Justice:Trial-Hearing":102,
                
                "Justice:Charge-Indict":96,
                "Transaction:Transfer-Ownership":92,
                "Personnel:Start-Position":90,
                "Justice:Sentence":83,
                "Justice:Arrest-Jail":77,
                "Life:Marry":65,
                "Conflict:Demonstrate":65,
                "Justice:Convict":62,
                "Justice:Sue":54,
                "Life:Be-Born":44,
                "Justice:Release-Parole":39,
                "Business:Declare-Bankruptcy":34,
                "Business:End-Org":31,
                "Justice:Appeal":30,
                "Business:Start-Org":29,
                "Justice:Fine":22,
                "Life:Divorce":20,
                "Justice:Execute":14,
                "Business:Merge-Org":14,
                "Personnel:Nominate":11,
                "Justice:Acquit":5,
                "Justice:Extradite":3,
                "Justice:Pardon":2,
                "Justice":102+100,
                "Life":511+100,
                "Business":0,
                "Personnel":100+158,
                "Contact":112+200,
                "Conflict":1245+100,
                "Movement":603+100,
                "Transaction":127+100,
                "event_type":102+511+158+112+200+1245+603+127
} 
# 34 event triggers
TRIGGERS_ACE = ['Business:Merge-Org',
            'Business:Start-Org',
            'Business:Declare-Bankruptcy',
            'Business:End-Org',
            'Justice:Pardon',
            'Justice:Extradite',
            'Justice:Execute',
            'Justice:Fine',
            'Justice:Trial-Hearing',
            'Justice:Sentence',
            'Justice:Appeal',
            'Justice:Convict',
            'Justice:Sue',
            'Justice:Release-Parole',
            'Justice:Arrest-Jail',
            'Justice:Charge-Indict',
            'Justice:Acquit',
            'Conflict:Demonstrate',
            'Conflict:Attack',
            'Contact:Phone-Write',
            'Contact:Meet',
            'Personnel:Start-Position',
            'Personnel:Elect',
            'Personnel:End-Position',
            'Personnel:Nominate',
            'Transaction:Transfer-Ownership',
            'Transaction:Transfer-Money',
            'Life:Marry',
            'Life:Divorce',
            'Life:Be-Born',
            'Life:Die',
            'Life:Injure',
            'Movement:Transport']
# using for naming module
naming_unlabel_trigger_ace = [
    'merge organization',
    'start organization',
    'bankruptcy',
    'end organization',
    'pardon',
    'extradition',
    'execution',
    'fine',
    'sentence',
    'appeal',
    'conviction',
    'sue',
    'charge parole',
    'arrest',
    'charge indict',
    'acquit',
    'demostrate',
    'start position',
    'nomination',
    'transfer ownership',
    'marriage',
    'divorce',
    'birth'
]
# top10
LABEL_TRIGGERS_ACE = ['Justice:Trial-Hearing',
                  'Life:Die',
                  'Transaction:Transfer-Money',
                  'Life:Injure',
                  'Personnel:End-Position',
                  'Personnel:Elect',
                  'Contact:Meet',
                  'Contact:Phone-Write',
                  'Movement:Transport',
                  'Conflict:Attack']

UNLABEL_TRIGGERS_ACE = [
    'Business:Merge-Org',
    'Business:Start-Org',
    'Business:Declare-Bankruptcy',
    'Business:End-Org',
    'Justice:Pardon',
    'Justice:Extradite',
    'Justice:Execute',
    'Justice:Fine',
    'Justice:Sentence',
    'Justice:Appeal',
    'Justice:Convict',
    'Justice:Sue',
    'Justice:Release-Parole',
    'Justice:Arrest-Jail',
    'Justice:Charge-Indict',
    'Justice:Acquit',
    'Conflict:Demonstrate',
    'Personnel:Start-Position',
    'Personnel:Nominate',
    'Transaction:Transfer-Ownership',
    'Life:Marry',
    'Life:Divorce',
    'Life:Be-Born'
]

TRIGGERS_ERE = ['Conflict:Attack', 
    'Movement:Transport-Person', 
    'Transaction:Transfer-Money', 
    'Contact:Contact', 
    'Life:Die', 
    'Contact:Broadcast', 
    'Transaction:Transfer-Ownership', 
    'Contact:Meet', 
    'Personnel:End-Position', 
    'Contact:Correspondence',
    'Justice:Arrest-Jail', 
    'Personnel:Start-Position', 
    'Justice:Trial-Hearing', 
    'Personnel:Elect', 
    'Justice:Charge-Indict', 
    'Manufacture:Artifact', 
    'Transaction:Transaction', 
    'Conflict:Demonstrate',
    'Justice:Sentence', 
    'Life:Marry', 
    'Justice:Convict', 
    'Movement:Transport-Artifact',
    'Life:Be-Born', 
    'Justice:Release-Parole', 
    'Life:Injure', 
    'Justice:Sue',
    'Justice:Pardon', 
    'Personnel:Nominate', 
    'Justice:Execute',
    'Business:Start-Org', 
    'Business:End-Org',
    'Life:Divorce', 
    'Justice:Acquit', 
    'Justice:Extradite', 
    'Business:Merge-Org', 
    'Justice:Appeal', 
    'Justice:Fine',
    'Business:Declare-Bankruptcy']
# top10
LABEL_TRIGGERS_ERE = ['Conflict:Attack', 
    'Movement:Transport-Person', 
    'Transaction:Transfer-Money', 
    'Contact:Contact', 
    'Life:Die', 
    'Contact:Broadcast', 
    'Transaction:Transfer-Ownership', 
    'Contact:Meet', 
    'Personnel:End-Position', 
    'Contact:Correspondence']

UNLABEL_TRIGGERS_ERE =  ['Justice:Arrest-Jail', 
                        'Personnel:Start-Position', 
                        'Justice:Trial-Hearing', 
                        'Personnel:Elect', 
                        'Justice:Charge-Indict', 
                        'Manufacture:Artifact', 
                        'Transaction:Transaction', 
                        'Conflict:Demonstrate',
                        'Justice:Sentence', 
                        'Life:Marry', 
                        'Justice:Convict', 
                        'Movement:Transport-Artifact',
                        'Life:Be-Born', 
                        'Justice:Release-Parole', 
                        'Life:Injure', 
                        'Justice:Sue',
                        'Justice:Pardon', 
                        'Personnel:Nominate', 
                        'Justice:Execute',
                        'Business:Start-Org', 
                        'Business:End-Org', 
                        'Life:Divorce', 
                        'Justice:Acquit', 
                        'Justice:Extradite', 
                        'Business:Merge-Org', 
                        'Justice:Appeal', 
                        'Justice:Fine',
                        'Business:Declare-Bankruptcy']

naming_unlabel_trigger_ere = [
                        'arrest jail', 
                        'start position', 
                        'trial hearing', 
                        'elect', 
                        'charge indict', 
                        'artifact', 
                        'transaction', 
                        'demonstrate',
                        'sentence', 
                        'marry', 
                        'convict', 
                        'transport artifact',
                        'born', 
                        'release parole', 
                        'injure', 
                        'sue',
                        'pardon', 
                        'nominate', 
                        'execute',
                        'start organization', 
                        'end organization', 
                        'divorce', 
                        'acquit', 
                        'extradite', 
                        'merge organization', 
                        'appeal', 
                        'fine',
                        'declare bankruptcy'
]
ere_structure = [        
            [["Life",None],["Life:Die",None]],
            [["Contact",None],["Contact:Broadcast",None]],
            [["Movement", None],["Movement:Transport-Person",None]],
            [["Transaction",None],["Transaction:Transfer-Money",None]],
            [["Conflict",None],["Conflict:Attack",None]],
            [["Contact",None],["Contact:Correspondence",None]],
            [['Transaction',None],['Transaction:Transfer-Ownership',None]],
            [["Personnel",None],["Personnel:End-Position",None]],
            [["Contact",None],["Contact:Meet",None]],
            [['Contact',None],['Contact:Contact',None]],
            
            [["event_type",None],["Life",None]],
            [["event_type",None],["Movement",None]],
            [["event_type",None],["Transaction",None]],
            [["event_type",None],["Conflict",None]],
            [["event_type",None],["Contact",None]],
            [["event_type",None],["Personnel",None]]
    ]

ere_structure_test = [
    [["Justice",None],["Justice:Arrest-Jail",None]],
    [["Personnel",None],["Personnel:Start-Position",None]],
    [['Justice',None],['Justice:Trial-Hearing',None]],
    [["Personnel",None],["Personnel:Elect",None]],
    [["Justice",None],["Justice:Charge-Indict",None]],
    [["Manufacture",None],["Manufacture:Artifact",None]],
    [['Transaction',None],['Transaction:Transaction',None]],
    [['Conflict',None],['Conflict:Demonstrate',None]],
    [['Justice',None],['Justice:Sentence',None]],
    [["Life",None],["Life:Marry",None]],
    [['Justice',None],['Justice:Convict',None]],
    [["Movement",None], ["Movement:Transport-Artifact",None]],
    [["Life",None],["Life:Be-Born",None]],
    [["Justice",None],["Justice:Release-Parole",None]],
    [["Life",None],["Life:Injure",None]],
    [["Justice",None],["Justice:Sue",None]],
    [["Justice",None],["Justice:Pardon",None]],
    [["Personnel",None],["Personnel:Nominate",None]],
    [["Justice",None],["Justice:Execute",None]],
    [["Business",None],["Business:Start-Org",None]],
    [["Business",None],["Business:Merge-Org",None]],
    [['Business',None],['Business:End-Org',None]],
    [["Life",None],["Life:Divorce",None]],
    [['Justice',None],['Justice:Acquit',None]],
    [["Justice",None],["Justice:Appeal",None]],
    [["Justice",None],["Justice:Extradite",None]],
    [["Business",None],["Business:Declare-Bankruptcy",None]],
    [["Justice",None],["Justice:Fine",None]],
]

NUM_LABEL_ERE = {"Conflict:Attack":1224,
                "Movement:Transport-Person":633,
                "Transaction:Transfer-Money":578,
                "Contact:Contact":521,
                "Life:Die":390,
                "Contact:Broadcast":338,
                "Transaction:Transfer-Ownership":280,
                "Contact:Meet":261,
                "Personnel:End-Position":199,
                "Contact:Correspondence":195,
                
                "Justice:Arrest-Jail":130,
                "Personnel:Start-Position":129,
                "Justice:Trial-Hearing":110,
                "Personnel:Elect":106,
                "Justice:Charge-Indict":105,
                "Manufacture:Artifact":104,
                "Transaction:Transaction":87,
                "Conflict:Demonstrate":80,
                "Justice:Sentence":69,
                "Life:Marry":63,
                "Justice:Convict":61,
                "Movement:Transport-Artifact":61,
                "Life:Be-Born":59,
                "Justice:Release-Parole":51,
                "Life:Injure":50,
                "Justice:Sue":46,
                "Justice:Pardon":36,
                "Personnel:Nominate":34,
                "Justice:Execute":34,
                "Business:Start-Org":32,
                "Business:End-Org":30,
                "Life:Divorce":25,
                "Justice:Acquit":22,
                "Justice:Extradite":22,
                "Business:Merge-Org":14,
                "Justice:Appeal":13,
                "Justice:Fine":11,
                "Business:Declare-Bankruptcy":5,
                "Conflict":1224+100, 
                "Movement":633+100,
                "Transaction":578+280,
                "Contact":521+338+261,
                "Life":390+100,
                "Personnel":199+100,
                "event_type":1224+633+578+521+390+338+280+261+199}

TRIGGERS_MAVEN = ['Causation', 'Process_start', 'Attack', 
    'Hostile_encounter', 'Catastrophe', 'Motion', 
    'Competition', 'Killing', 'Process_end', 'Social_event', 
    'Conquering', 'Statement', 'Self_motion', 'Arriving', 
    'Destroying', 'Coming_to_be', 'Bodily_harm', 'Death', 'Creating', 'Military_operation',
    'Damaging', 'Cause_change_of_strength', 
    'Cause_change_of_position_on_a_scale', 'Hold', 'Control', 'Earnings_and_losses', 
    'Getting', 'Becoming', 'Arranging', 'Know', 'Preventing_or_letting', 'Presence', 
    'Escaping', 'Defending', 'Action', 'Motion_directional', 'Cause_to_be_included', 
    'Change', 'Traveling', 'Placing', 'Participation', 'Influence', 'Change_of_leadership', 
    'Judgment_communication', 'Expressing_publicly', 'Name_conferral', 'Request', 'Giving', 
    'Supporting', 'Recording', 'Removing', 'Agree_or_refuse_to_act', 'Using', 'Supply', 'Communication', 
    'Reporting', 'Choosing', 'Sending', 'Bringing', 'Departing', 'Use_firearm', 'Assistance',
    'Cause_to_make_progress', 'Perception_active', 'Deciding', 'Building', 'Dispersal',
    'Manufacturing', 'Come_together', 'Arrest', 'Cause_to_amalgamate', 'Violence', 
    'Hindering', 'Response', 'Aiming', 'Receiving', 'Achieve', 'Recovering', 'Expansion', 
    'Change_event_time', 'Scrutiny', 'Besieging', 'Check', 'Publishing', 'Becoming_a_member',
    'Openness', 'Criminal_investigation', 'Committing_crime', 'Collaboration', 
    'Coming_to_believe', 'Connect', 'Surrendering', 'Being_in_operation', 'Terrorism', 
    'Legal_rulings', 'Warning', 'Confronting_problem', 'Preserving', 'Convincing', 'Temporary_stay',
    'Sign_agreement', 'GiveUp', 'Quarreling', 'Change_sentiment', 'Telling', 'Legality', 'Protest',
    'Resolve_problem', 'Commitment', 'Employment', 'Testing', 'Rescuing', 'Commerce_sell', 'Emptying', 
    'Body_movement', 'Releasing', 'GetReady', 'Education_teaching', 'Reveal_secret', 'Hiding_objects',
    'Surrounding', 'Filling', 'Forming_relationships', 'Writing', 'Bearing_arms', 'Expend_resource', 
    'Commerce_pay', 'Reforming_a_system', 'Patrolling', 'Rewards_and_punishments', 'Cost', 'Research', 
    'Adducing', 'Limiting', 'Kidnapping', 'Wearing', 'Cure', 'Create_artwork', 'Exchange',
    'Having_or_lacking_access', 'Imposing_obligation', 'Robbery', 'Award', 'Containing', 'Prison',
    'Revenge', 'Commerce_buy', 'Rite', 'Carry_goods', 'Submitting_documents', 'Practice', 'Labeling',
    'Lighting', 'Scouring', 'Justifying', 'Ratification', 'Suspicion', 'Vocalizations', 'Theft', 'Renting',
    'Ingestion', 'Incident', 'Risk', 'Extradition', 'Institutionalization', 'Emergency', 'Breathing', 'Change_tool'
]

# LABEL_TRIGGERS_MAVEN = ['Causation', 'Process_start', 'Attack', 
#     'Hostile_encounter', 'Catastrophe', 'Motion', 
#     'Competition', 'Killing', 'Process_end', 'Social_event', 
#     'Conquering', 'Statement', 'Self_motion', 'Arriving', 
#     'Destroying', 'Coming_to_be', 'Bodily_harm', 'Death', 'Creating', 'Military_operation',
#     'Damaging', 'Cause_change_of_strength', 
#     'Cause_change_of_position_on_a_scale', 'Hold', 'Control', 'Earnings_and_losses', 
#     'Getting', 'Becoming', 'Arranging', 'Know'
# ] 

# UNLABEL_TRIGGERS_MAVEN = ['Preventing_or_letting', 'Presence', 
#     'Escaping', 'Defending', 'Action', 'Motion_directional', 'Cause_to_be_included', 
#     'Change', 'Traveling', 'Placing', 'Participation', 'Influence', 'Change_of_leadership', 
#     'Judgment_communication', 'Expressing_publicly', 'Name_conferral', 'Request', 'Giving', 
#     'Supporting', 'Recording'
# ]

LABEL_TRIGGERS_MAVEN = ['Causation', 'Process_start', 'Attack', 
    'Hostile_encounter', 'Catastrophe', 'Motion', 
    'Competition', 'Killing', 'Process_end', 'Social_event','Conquering', 'Statement', 'Self_motion', 'Arriving', 
    'Destroying', 'Coming_to_be', 'Bodily_harm', 'Death', 'Creating', 'Military_operation'
] 

UNLABEL_TRIGGERS_MAVEN = [
    'Damaging', 'Cause_change_of_strength', 
    'Cause_change_of_position_on_a_scale', 'Hold', 'Control', 'Earnings_and_losses', 
    'Getting', 'Becoming', 'Arranging', 'Know', 'Preventing_or_letting', 'Presence', 
    'Escaping', 'Defending', 'Action', 'Motion_directional', 'Cause_to_be_included', 
    'Change', 'Traveling', 'Placing', 'Participation', 'Influence', 'Change_of_leadership', 
    'Judgment_communication', 'Expressing_publicly', 'Name_conferral', 'Request', 'Giving', 
    'Supporting', 'Recording','Removing', 'Agree_or_refuse_to_act', 'Using', 'Supply', 'Communication', 
    'Reporting', 'Choosing', 'Sending', 'Bringing', 'Departing'
]


maven_structure = [        
            [["Violence",None],["Attack",None]],
            [["Violence",None],["Military_operation",None]],
            [["Violence",None],["Hostile_encounter",None]],
            [["Violence",None],["Killing",None]],
            
            [["Motion_vir",None],["Motion",None]],
            [["Motion_vir",None],["Self_motion",None]],
            [["Motion_vir",None],["Arriving",None]],

            [["Communication_vir",None],["Statement",None]],

            [["Action_vir",None],["Violence",None]],
            [["Action_vir",None],["Communication_vir",None]],
            [["Action_vir",None],["Social_event",None]],
            [["Action_vir",None],["Creating",None]],
            [["Action_vir",None],["Motion_vir",None]],
            
            [["Scenario",None],["Catastrophe",None]],
            [["Scenario",None],["Competition",None]],
            [["Scenario",None],["Process_end",None]],
            [["Scenario",None],["Process_start",None]],

            [["Influence_vir",None],["Causation",None]],
            [["Influence_vir",None],["Conquering",None]],
            
            [["AlterBadState",None],["Bodily_harm",None]],
            [["AlterBadState",None],["Destroying",None]],
            [["AlterBadState",None],["Death",None]],

            [["Change_vir",None],["Influence_vir",None]],
            [["Change_vir",None],["Coming_to_be",None]],
            [["Change_vir",None],["AlterBadState",None]],

            [["event_type",None],["Action_vir",None]],
            [["event_type",None],["Scenario",None]],
            [["event_type",None],["Change_vir",None]]


    ]

maven_structure_test = [
    [['Change_vir:AlterBadState', None], ['Damaging', None]], 
    [['Change_vir', None], ['Cause_change_of_strength', None]], 
    [['Change_vir', None], ['Cause_change_of_position_on_a_scale', None]], 
    [['Action_vir', None], ['Hold', None]], 
    [['Change_vir:Influence_vir', None], ['Control', None]], 
    [['event_type', None], ['Earnings_and_losses', None]], 
    [['event_type', None], ['Getting', None]], 
    [['Change_vir', None], ['Becoming', None]], 
    [['Action_vir', None], ['Arranging', None]], 
    [['Action_vir', None], ['Know', None]], 
    [['Change_vir:Influence_vir', None], ['Preventing_or_letting', None]], 
    [['Change_vir:Coming_to_be', None], ['Presence', None]], 
    [['Action_vir:Motion_vir:Self_motion', None], ['Escaping', None]], 
    [['Action_vir:Violence', None], ['Defending', None]], 
    [['Action_vir', None], ['Action', None]], 
    [['Action_vir:Motion_vir', None], ['Motion_directional', None]], 
    [['Change_vir', None], ['Cause_to_be_included', None]], 
    [['Change_vir', None], ['Change', None]], 
    [['Action_vir:Motion_vir', None], ['Traveling', None]], 
    [['Action_vir', None], ['Placing', None]], 
    [['Change_vir', None], ['Participation', None]], 
    [['Change_vir:Influence_vir', None], ['Influence', None]], 
    [['Change_vir', None], ['Change_of_leadership', None]], 
    [['Action_vir', None], ['Judgment_communication', None]], 
    [['Action_vir:Communication_vir', None], ['Expressing_publicly', None]],
    [['Action_vir', None], ['Name_conferral', None]], 
    [['event_type', None], ['Request', None]],
    [['event_type', None], ['Giving', None]], 
    [['event_type', None], ['Supporting', None]], 
    [['Action_vir:Creating', None], ['Recording', None]], 
    [['Action_vir', None], ['Removing', None]], 
    [['event_type', None], ['Agree_or_refuse_to_act', None]], 
    [['Action_vir', None], ['Using', None]], 
    [['event_type', None], ['Supply', None]], 
    [['Action_vir:Communication_vir', None], ['Communication', None]],
    [['Action_vir:Communication_vir', None], ['Reporting', None]], 
    [['Action_vir', None], ['Choosing', None]], 
    [['event_type', None], ['Sending', None]],
    [['event_type', None], ['Bringing', None]],
    [['Action_vir:Motion_vir', None], ['Departing', None]]
]


UNLABEL_TRIGGERS_MAVEN_NAME = [
    'Change_vir:AlterBadState:Damaging', 
    'Change_vir:Cause_change_of_strength', 
    'Change_vir:Cause_change_of_position_on_a_scale', 
    'Action_vir:Hold', 
    'Change_vir:Influence_vir:Control', 
    'event_type:Earnings_and_losses', 
    'event_type:Getting', 
    'Change_vir:Becoming', 
    'Action_vir:Arranging', 
    'Action_vir:Know', 
    'Change_vir:Influence_vir:Preventing_or_letting', 
    'Change_vir:Coming_to_be:Presence', 
    'Action_vir:Motion_vir:Self_motion:Escaping', 
    'Action_vir:Violence:Defending', 
    'Action_vir:Action', 
    'Action_vir:Motion_vir:Motion_directional', 
    'Change_vir:Cause_to_be_included', 
    'Change_vir:Change', 
    'Action_vir:Motion_vir:Traveling', 
    'Action_vir:Placing', 
    'Change_vir:Participation', 
    'Change_vir:Influence_vir:Influence', 
    'Change_vir:Change_of_leadership', 
    'Action_vir:Judgment_communication', 
    'Action_vir:Communication_vir:Expressing_publicly',
    'Action_vir:Name_conferral', 
    'event_type:Request',
    'event_type:Giving', 
    'event_type:Supporting', 
    'Action_vir:Creating:Recording', 
    'Action_vir:Removing', 
    'event_type:Agree_or_refuse_to_act', 
    'Action_vir:Using', 
    'event_type:Supply', 
    'Action_vir:Communication_vir:Communication',
    'Action_vir:Communication_vir:Reporting', 
    'Action_vir:Choosing', 
    'event_type:Sending',
    'event_type:Bringing',
    'Action_vir:Motion_vir:Departing'
]